// <auto-generated />
namespace AutoLote.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DosBaseDatos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DosBaseDatos));
        
        string IMigrationMetadata.Id
        {
            get { return "201509200922453_DosBaseDatos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
